plugins {
    id "com.android.application"
}

android {
    namespace "com.byw.worldquizzchallenge"
    compileSdk 36

    defaultConfig {
        applicationId "com.byw.worldquizzchallenge"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}

dependencies {
    implementation "com.google.androidbrowserhelper:androidbrowserhelper:2.5.0"
}
